# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid-19App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid-19App
  pod 'SwiftCharts', '~> 0.6.5'

end
